// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinBackend.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFinBackend.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20260419031542_AddGroupSplitConfigAndMonthClose")]
    partial class AddGroupSplitConfigAndMonthClose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFinBackend.Model.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<float>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("expense_pk");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Expense", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("expense_category_pk");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseCategory", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseSplitConfig", b =>
                {
                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    b.Property<int>("GroupSplitConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("group_split_config_id");

                    b.HasKey("ExpenseId")
                        .HasName("expense_split_config_pk");

                    b.HasIndex("GroupSplitConfigId");

                    b.ToTable("ExpenseSplitConfig", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseSplitShare", b =>
                {
                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.HasKey("ExpenseId", "UserId")
                        .HasName("expense_split_share_pk");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseSplitShare", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("group_pk");

                    b.HasIndex("UserId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("GroupId", "UserId")
                        .HasName("group_member_pk");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMember", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMemberConfig", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("numeric")
                        .HasColumnName("salary");

                    b.HasKey("GroupId", "UserId")
                        .HasName("group_member_config_pk");

                    b.ToTable("GroupMemberConfig", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMonthClose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("group_month_close_pk");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMonthClose", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMonthCloseConfirmation", b =>
                {
                    b.Property<int>("GroupMonthCloseId")
                        .HasColumnType("integer")
                        .HasColumnName("group_month_close_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.HasKey("GroupMonthCloseId", "UserId")
                        .HasName("group_month_close_confirmation_pk");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMonthCloseConfirmation", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupSplitConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer")
                        .HasColumnName("split_type");

                    b.HasKey("Id")
                        .HasName("group_split_config_pk");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupSplitConfig", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupSplitConfigShare", b =>
                {
                    b.Property<int>("GroupSplitConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("group_split_config_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.HasKey("GroupSplitConfigId", "UserId")
                        .HasName("group_split_config_share_pk");

                    b.HasIndex("UserId");

                    b.ToTable("GroupSplitConfigShare", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MyFinBackend.Model.Expense", b =>
                {
                    b.HasOne("MyFinBackend.Model.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_category");

                    b.HasOne("MyFinBackend.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expense_group");

                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_user");

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseCategory", b =>
                {
                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_category_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseSplitConfig", b =>
                {
                    b.HasOne("MyFinBackend.Model.Expense", "Expense")
                        .WithOne()
                        .HasForeignKey("MyFinBackend.Model.ExpenseSplitConfig", "ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_split_config");

                    b.HasOne("MyFinBackend.Model.GroupSplitConfig", "GroupSplitConfig")
                        .WithMany()
                        .HasForeignKey("GroupSplitConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_split_config_group_split");

                    b.Navigation("Expense");

                    b.Navigation("GroupSplitConfig");
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseSplitShare", b =>
                {
                    b.HasOne("MyFinBackend.Model.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_split_share_expense");

                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_split_share_user");

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.Group", b =>
                {
                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_owner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMember", b =>
                {
                    b.HasOne("MyFinBackend.Model.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_group");

                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMemberConfig", b =>
                {
                    b.HasOne("MyFinBackend.Model.GroupMember", "GroupMember")
                        .WithOne()
                        .HasForeignKey("MyFinBackend.Model.GroupMemberConfig", "GroupId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_member_config");

                    b.Navigation("GroupMember");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMonthClose", b =>
                {
                    b.HasOne("MyFinBackend.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_month_close_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMonthCloseConfirmation", b =>
                {
                    b.HasOne("MyFinBackend.Model.GroupMonthClose", "GroupMonthClose")
                        .WithMany("Confirmations")
                        .HasForeignKey("GroupMonthCloseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_month_close_confirmation_close");

                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_month_close_confirmation_user");

                    b.Navigation("GroupMonthClose");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupSplitConfig", b =>
                {
                    b.HasOne("MyFinBackend.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_split_config_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupSplitConfigShare", b =>
                {
                    b.HasOne("MyFinBackend.Model.GroupSplitConfig", "GroupSplitConfig")
                        .WithMany("Shares")
                        .HasForeignKey("GroupSplitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_split_config_share_config");

                    b.HasOne("MyFinBackend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_split_config_share_user");

                    b.Navigation("GroupSplitConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinBackend.Model.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MyFinBackend.Model.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupMonthClose", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("MyFinBackend.Model.GroupSplitConfig", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyFinBackend.Model.User", b =>
                {
                    b.Navigation("ExpenseCategories");

                    b.Navigation("Expenses");

                    b.Navigation("GroupMemberships");

                    b.Navigation("OwnedGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
