name: Trigger Deploy Webhook

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
